### PR TITLE
make basicConfig happy again

### PR DESCRIPTION
**Pull request by roblatham00**
for some reason I do not understand basicConfig kept giving me an error about
both 'filename' and 'stream' being provided.   So I took a big hammer and
removed both those parameters.

### CODE REVIEW

**Comment by lee218llnl** [comment]
Did you see my previous comment? I think we can put some exception handling in there to accommodate the error you see, but I was hoping to at least see your error output so I know what exception to catch. I do not plan on merging this PR as it stands, because this removes the ability to dump the log to a file.

**Comment by roblatham00** [comment]
Sorry for not responding more promptly.  

Now that I try to retrace my steps, this seems to be more a python3/python2 thing.  works great with python2.7.17

with python3 and stat-4.1.0  here's the backtrace
```
failed to determine core file type: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-10.2.0/stat-4.1.0-wn2frxd57sysvqvapa65yd5sqflvi3sr/lib/python3.6/site-packages/STATmain.py", line 134, in <module>
    STATmerge_main(sys.argv[1:])
  File "/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-10.2.0/stat-4.1.0-wn2frxd57sysvqvapa65yd5sqflvi3sr/lib/python3.6/site-packages/core_file_merger.py", line 650, in STATmerge_main
    merger = CoreMerger(CoreTrace, CoreMergerArgs)
  File "/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-10.2.0/stat-4.1.0-wn2frxd57sysvqvapa65yd5sqflvi3sr/lib/python3.6/site-packages/stat_merge_base.py", line 241, in __init__
    self.options, self.trace_files = self.args.parse_args()
  File "/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-10.2.0/stat-4.1.0-wn2frxd57sysvqvapa65yd5sqflvi3sr/lib/python3.6/site-packages/stat_merge_base.py", line 226, in parse_args
    self.error_check(options)
  File "/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-10.2.0/stat-4.1.0-wn2frxd57sysvqvapa65yd5sqflvi3sr/lib/python3.6/site-packages/core_file_merger.py", line 524, in error_check
    new_loglevel = init_logging(options["loglevel"], options["logfile"])    #Initialize the logging module
  File "/autofs/nccs-svm1_home1/robl/src/spack/opt/spack/linux-rhel8-power9le/gcc-10.2.0/stat-4.1.0-wn2frxd57sysvqvapa65yd5sqflvi3sr/lib/python3.6/site-packages/core_file_merger.py", line 586, in init_logging
    logging.basicConfig(level=input_loglevel, format=log_format, datefmt=log_date, filename=log_file, stream=log_stream, filemode='w')
  File "/usr/lib64/python3.6/logging/__init__.py", line 1798, in basicConfig
    raise ValueError("'stream' and 'filename' should not be "
ValueError: 'stream' and 'filename' should not be specified together
```

**Comment by lee218llnl** [comment]
can you let me know if #41 works for your python3 case?

**Comment by roblatham00** [comment]
Thanks that takes care of the exception, and commit e2d7f360c21b6 takes care of the "bytes-like object" warning.  

python3 still gives me a hang talking to gdb, but that's a separate issue.  The big hammer in this pull request is no longer necessary.

**Pull request closed without merging**
